name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          # for mac m1
          node-version: '16.7.0'

      - name: Install Dependencies
        run: npm install
        
      - name: Run Jest Tests
        run : npm run test
